version: '3'

services:
  web:
    build: 
      context: ./docker
    ports:
      - '9000:80'
      - '9002:8089'
    links:
      - db
    volumes:
      - .:/var/www/:rw
  db:
    image: mysql:8
    ports:
      - '8889:3306'
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysqldb_volume:/var/lib/mysql/

volumes:
  mysqldb_volume: