version: '3'

services:
  web:
    build: 
      context: ./docker
    ports:
      - '8081: 80'
      - '8082: 8089'
    links:
      - db
    volumes:
      - .:/var/www/
  db:
    image: mysql:8
    ports:
      - '8889:3306'
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql/
	
