version: '3.3'

services:
  web:
    build: 
      context: ./docker
    ports:
      - '9000:80'
      - '9002:8089'
    links:
      - db
    volumes:
      - .:/var/www/:rw
  db:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    command: --disable-partition-engine-check
    ports:
      - '9001:3306'
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysqldb_volume:/var/lib/mysql/

volumes:
  mysqldb_volume: