FROM php:7.2-apache

MAINTAINER Mahdi Gueffaz

ENV COMPOSER_ALLOW_SUPERUSER=1

EXPOSE 80
WORKDIR /app

RUN apt-get update -qy && \
    apt-get install -y \
    vim \
    git \
    libicu-dev \
    unzip \
    zip && \ 
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# PHP Extensions
RUN docker-php-ext-install -j$(nproc) opcache pdo_mysql
#ADD conf/php.ini /usr/local/etc/php/conf.d/app.ini

# Apache
RUN a2enmod rewrite remoteip
ADD default.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/

Expose 80 8089

WORKDIR /var/www/

# By default start up apache in the foreground, override with /bin/bash for interative.
CMD /usr/sbin/apache2ctl -D FOREGROUND