<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2xv74f\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2xv74f/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2xv74f.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2xv74f\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX2xv74f\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X2xv74f',
    'container.build_id' => 'e4464c0a',
    'container.build_time' => 1569261078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2xv74f');
