<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0t8dUHw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0t8dUHw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0t8dUHw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0t8dUHw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0t8dUHw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0t8dUHw',
    'container.build_id' => 'c32aef4d',
    'container.build_time' => 1565642702,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0t8dUHw');
