<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'easyadmin.security.authorization_checker' shared service.

include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Security/AuthorizationChecker.php';

return $this->services['easyadmin.security.authorization_checker'] = new \EasyCorp\Bundle\EasyAdminBundle\Security\AuthorizationChecker(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
