api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # The title of the API.
    title: 'Aviation plateform'
    # The description of the API.
    description: 'Aviation application plateform'

    # The version of the API.
    version: '1.0.0'